version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=file:./dev.db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
