version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./backend/backend:/backend
    command: python3 /backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data:
